config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'persons/profile'
  get 'persons/profile', as: 'user_root'
  resources :periods
  resources :calendars, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/ovulation.rb
class Ovulation < ApplicationRecord
end

app/models/period.rb
class Period < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  def index
    @periods = Period.all
  end
  def show
    @period = Period.find(params[:id])
  end

  def new
    @period = Period.new
  end

  def create
    @period = Period.new(params[:menses_start, :menses_end])
    if @period.save
      redirect_to @period, notice: "Created period."
    else
      render :new
    end
  end

  def edit
    @period = Period.find(params[:id])
  end

  def update
    @period= Period.find(params[:id])
    if @period.update_attributes(params[:menses_start, :menses_end])
      redirect_to @period, notice: "Updated period."
    else
      render :edit
    end
  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/calendars/show.html.erb
<h1>Calendar</h1>
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyDairy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/periods/index.html.erb
<% provide(:title, 'All uperiods') %>
<h1>All Periods</h1>

<ul class="periods">
  <% @periods.each do |period| %>
    <h3>
       <%=period.menses_start %>
       <%=period.menses_end %>
    </h3>
  <% end %>
</ul>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>